# Generated by Django 5.0.14 on 2025-11-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, help_text='Optional description or alias')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payee',
                'verbose_name_plural': 'Payees',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='is_liquidity_relevant',
            field=models.BooleanField(default=True, help_text='Whether this account should be included in liquidity calculations (e.g., checking accounts: yes, loans/savings: no)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payee',
            field=models.ForeignKey(blank=True, help_text='Optional payment recipient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.payee'),
        ),
        migrations.AddField(
            model_name='recurringbooking',
            name='payee',
            field=models.ForeignKey(blank=True, help_text='Optional payment recipient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bookings', to='core.payee'),
        ),
    ]
