# Generated by Django 5.0.14 on 2025-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payee_account_is_liquidity_relevant_booking_payee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KIGateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name for identification', max_length=200)),
                ('base_url', models.URLField(help_text='Base URL for KIGate API')),
                ('api_key', models.CharField(help_text='API key for authentication', max_length=500)),
                ('max_tokens', models.PositiveIntegerField(default=2000, help_text='Maximum tokens for responses')),
                ('default_agent_name', models.CharField(blank=True, help_text='Default agent name to use', max_length=200)),
                ('default_provider', models.CharField(blank=True, help_text='Default AI provider (e.g., openai, anthropic)', max_length=100)),
                ('default_model', models.CharField(blank=True, help_text='Default model name', max_length=100)),
                ('default_user_id', models.CharField(blank=True, help_text='Default user ID for requests', max_length=200)),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Request timeout in seconds')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KIGate Configuration',
                'verbose_name_plural': 'KIGate Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpenAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name for identification', max_length=200)),
                ('api_key', models.CharField(help_text='OpenAI API key', max_length=500)),
                ('base_url', models.URLField(default='https://api.openai.com/v1', help_text='OpenAI API base URL')),
                ('default_model', models.CharField(default='gpt-4', help_text='Default text model', max_length=100)),
                ('default_vision_model', models.CharField(default='gpt-4-vision-preview', help_text='Default vision model', max_length=100)),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Request timeout in seconds')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenAI Configuration',
                'verbose_name_plural': 'OpenAI Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
