# Generated by Django 5.0.14 on 2025-11-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kigateconfig_openaiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='finoa_uploads/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Hochgeladen'), ('AI_PROCESSING', 'In Verarbeitung'), ('AI_DONE', 'Analyse abgeschlossen'), ('REVIEW_PENDING', 'Zur Prüfung'), ('BOOKED', 'Verbucht'), ('ERROR', 'Fehler')], default='UPLOADED', max_length=32)),
                ('source', models.CharField(blank=True, help_text="z.B. 'web', 'mobile', 'api'.", max_length=50)),
                ('ai_result_openai', models.JSONField(blank=True, null=True)),
                ('ai_result_kigate', models.JSONField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suggested_currency', models.CharField(blank=True, default='EUR', max_length=8)),
                ('suggested_date', models.DateField(blank=True, help_text='Beleg-/Buchungsdatum aus der Analyse.', null=True)),
                ('suggested_description', models.CharField(blank=True, max_length=255)),
                ('suggested_is_recurring', models.BooleanField(default=False, help_text='Wird in der KI-Antwort vorgeschlagen als wiederkehrende Zahlung.')),
                ('suggestion_confidence', models.FloatField(blank=True, help_text='Gesamteinschätzung der KI (0–1).', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_document', to='core.booking')),
                ('suggested_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_suggested_account', to='core.account')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_suggested_category', to='core.category')),
                ('suggested_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_suggested_payee', to='core.payee')),
            ],
            options={
                'verbose_name': 'Document Upload',
                'verbose_name_plural': 'Document Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
