# Generated by Django 5.0.14 on 2025-11-22 16:11

from django.db import migrations


def update_vision_model(apps, schema_editor):
    """Update deprecated gpt-4-vision-preview to gpt-4o"""
    OpenAIConfig = apps.get_model('core', 'OpenAIConfig')
    OpenAIConfig.objects.filter(default_vision_model='gpt-4-vision-preview').update(
        default_vision_model='gpt-4o'
    )


def reverse_vision_model(apps, schema_editor):
    """
    Reverse migration - no-op since we don't want to revert to deprecated model.
    If you need to rollback, manually update OpenAIConfig records as needed.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documentupload'),
    ]

    operations = [
        migrations.RunPython(update_vision_model, reverse_vision_model),
    ]
