# Generated by Django 5.0.14 on 2025-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_openai_vision_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiconfig',
            name='default_vision_model',
            field=models.CharField(default='gpt-4o', help_text='Default vision model', max_length=100),
        ),
    ]
