# Generated by Django 5.0.14 on 2025-11-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_openaiconfig_default_vision_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of service')),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Duration in hours (e.g. 0.5, 1.0, 2.3)', max_digits=4)),
                ('activity', models.CharField(help_text='Description of activity', max_length=255)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in €/hour', max_digits=6)),
                ('billed', models.BooleanField(default=False, help_text='Whether this has been billed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payee', models.ForeignKey(help_text='Customer / Payment recipient', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.payee')),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
