# Generated by Django 5.0.14 on 2025-11-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgBrokerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name for identification', max_length=200)),
                ('api_key', models.CharField(help_text='IG API key', max_length=500)),
                ('username', models.CharField(help_text='IG account username/identifier', max_length=200)),
                ('password', models.CharField(help_text='IG account password', max_length=500)),
                ('account_type', models.CharField(choices=[('DEMO', 'Demo'), ('LIVE', 'Live')], default='DEMO', help_text='Account type (Demo or Live)', max_length=10)),
                ('account_id', models.CharField(blank=True, help_text='Specific account ID (if multiple accounts)', max_length=50)),
                ('api_base_url', models.URLField(blank=True, help_text='Custom API base URL (optional, auto-detected based on account type)')),
                ('default_oil_epic', models.CharField(blank=True, help_text='Default EPIC for oil trading (e.g., CC.D.CL.UNC.IP for WTI Crude)', max_length=100)),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Request timeout in seconds')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IG Broker Configuration',
                'verbose_name_plural': 'IG Broker Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
