# Generated by Django 5.0.14 on 2025-11-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_igbrokerconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Girokonto'), ('credit_card', 'Kreditkarte'), ('trading', 'Trading-Konto'), ('loan', 'Darlehen'), ('liability', 'Verbindlichkeit'), ('receivable', 'Forderung'), ('depot', 'Wertpapierdepot'), ('savings', 'Sparen'), ('insurance', 'Versicherungen')], max_length=50),
        ),
    ]
