# Generated by Django 5.0.14 on 2025-11-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_new_account_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MexcBrokerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name for identification', max_length=200)),
                ('api_key', models.CharField(help_text='MEXC API key', max_length=500)),
                ('api_secret', models.CharField(help_text='MEXC API secret', max_length=500)),
                ('account_type', models.CharField(choices=[('SPOT', 'Spot'), ('MARGIN', 'Margin')], default='SPOT', help_text='Account type (Spot or Margin)', max_length=10)),
                ('api_base_url', models.URLField(default='https://api.mexc.com', help_text='MEXC API base URL')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Request timeout in seconds')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MEXC Broker Configuration',
                'verbose_name_plural': 'MEXC Broker Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
