# Generated by Django 5.2.8 on 2025-11-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mexcbrokerconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mexcbrokerconfig',
            name='account_type',
            field=models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], default='SPOT', help_text='Account type (Spot or Futures)', max_length=10),
        ),
    ]
