# Generated by Django 5.0.14 on 2025-12-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_mexc_account_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrakenBrokerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name for identification', max_length=200)),
                ('api_key', models.CharField(help_text='Kraken API key', max_length=500)),
                ('api_secret', models.CharField(help_text='Kraken API secret', max_length=500)),
                ('account_type', models.CharField(choices=[('LIVE', 'Live'), ('DEMO', 'Demo')], default='DEMO', help_text='Account type (Live or Demo)', max_length=10)),
                ('rest_base_url', models.URLField(blank=True, help_text='REST API base URL (auto-detected based on account type if empty)')),
                ('charts_base_url', models.URLField(blank=True, help_text='Charts API base URL (auto-detected based on account type if empty)')),
                ('websocket_url', models.URLField(blank=True, help_text='WebSocket URL for real-time data (auto-detected based on account type if empty)')),
                ('default_symbol', models.CharField(default='PI_XBTUSD', help_text='Default trading symbol (e.g., PI_XBTUSD for Bitcoin)', max_length=50)),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Request timeout in seconds')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kraken Broker Configuration',
                'verbose_name_plural': 'Kraken Broker Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
