# Generated by Django 5.0.14 on 2025-11-25 16:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setup_type', models.CharField(choices=[('BREAKOUT', 'Breakout'), ('EIA_REVERSION', 'EIA-Reversion'), ('EIA_TRENDDAY', 'EIA-TrendDay')], max_length=50)),
                ('session_phase', models.CharField(choices=[('LONDON_CORE', 'London Core'), ('US_CORE', 'US Core'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post'), ('ASIAN', 'Asian Session')], max_length=50)),
                ('instrument', models.CharField(default='CL', max_length=50)),
                ('range_high', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('range_low', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('position_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ki_reasoning', models.TextField(blank=True, help_text='Kurze KI-Begründung')),
                ('gpt_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GPT Confidence Score (0-100%)', max_digits=5)),
                ('gpt_reasoning', models.TextField(blank=True, help_text='Ausführliche GPT-Begründung')),
                ('gpt_corrected_sl', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('gpt_corrected_tp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('gpt_corrected_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_status', models.CharField(choices=[('GREEN', 'Erlaubt'), ('YELLOW', 'Riskant'), ('RED', 'Verboten')], default='GREEN', max_length=10)),
                ('risk_allowed_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Risiko % vom Konto', max_digits=5, null=True)),
                ('risk_reasoning', models.TextField(blank=True, help_text='Risk Engine Begründung')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('EXECUTED', 'Ausgeführt'), ('SHADOW', 'Shadow'), ('REJECTED', 'Verworfen')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('LIVE', 'Live Trade'), ('SHADOW', 'Shadow Trade')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('CLOSED', 'Geschlossen'), ('CANCELLED', 'Abgebrochen')], default='OPEN', max_length=20)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('position_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.signal')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-opened_at'],
            },
        ),
    ]
