# Generated by Django 5.0.14 on 2025-11-26 08:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_at', models.DateTimeField(help_text='Timestamp of the last worker loop execution')),
                ('phase', models.CharField(choices=[('ASIA_RANGE', 'Asia Range'), ('LONDON_CORE', 'London Core'), ('US_CORE', 'US Core'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post'), ('FRIDAY_LATE', 'Friday Late'), ('OTHER', 'Other')], help_text='Current session phase', max_length=20)),
                ('epic', models.CharField(help_text='Current instrument EPIC (e.g., CC.D.CL.UNC.IP)', max_length=100)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=4, help_text='Last bid price', max_digits=10, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=4, help_text='Last ask price', max_digits=10, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=4, help_text='Current spread', max_digits=10, null=True)),
                ('setup_count', models.PositiveIntegerField(default=0, help_text='Number of setups found in last run')),
                ('diagnostic_message', models.TextField(blank=True, help_text='Human-readable diagnostic message (e.g., why no setups found)')),
                ('worker_interval', models.PositiveIntegerField(default=60, help_text='Expected interval between worker loops in seconds')),
            ],
            options={
                'verbose_name': 'Worker Status',
                'verbose_name_plural': 'Worker Status',
            },
        ),
        migrations.AlterField(
            model_name='signal',
            name='gpt_confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GPT Confidence Score (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
