# Generated by Django 5.0.14 on 2025-11-25 21:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='gpt_confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GPT Confidence Score (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
