# Generated by Django 5.0.14 on 2025-11-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_signal_gpt_confidence'),
        ('trading', '0002_worker_status'),
    ]

    operations = [
    ]
