# Generated by Django 5.0.14 on 2025-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='diagnostic_criteria',
            field=models.JSONField(blank=True, default=list, help_text='List of diagnostic criteria with pass/fail status (JSON)'),
        ),
    ]
