# Generated by Django 5.0.14 on 2025-11-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_add_diagnostic_criteria'),
        ('trading', '0003_merge_20251126_0939'),
    ]

    operations = [
    ]
