# Generated by Django 5.0.14 on 2025-11-26 10:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_add_diagnostic_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g., "US Crude Oil", "Gold", "Nasdaq 100")', max_length=100)),
                ('symbol', models.CharField(help_text='Short symbol (e.g., "CL", "GOLD", "NAS100")', max_length=50)),
                ('epic', models.CharField(help_text='Broker EPIC/Symbol for API calls (e.g., "CC.D.CL.UNC.IP")', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('commodity', 'Commodities'), ('index', 'Indices'), ('forex', 'Forex'), ('crypto', 'Crypto'), ('stock', 'Stocks'), ('other', 'Other')], default='commodity', help_text='Asset category for grouping', max_length=20)),
                ('strategy_type', models.CharField(choices=[('breakout_event', 'Breakout + Event')], default='breakout_event', help_text='Strategy to use for this asset', max_length=50)),
                ('tick_size', models.DecimalField(decimal_places=6, default=Decimal('0.01'), help_text='Minimum price movement (e.g., 0.01 for WTI)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this asset is actively traded by the worker')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading Asset',
                'verbose_name_plural': 'Trading Assets',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetBreakoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asia_range_start', models.CharField(default='00:00', help_text='Asia range start time (UTC, HH:MM format)', max_length=5)),
                ('asia_range_end', models.CharField(default='08:00', help_text='Asia range end time (UTC, HH:MM format)', max_length=5)),
                ('asia_min_range_ticks', models.PositiveIntegerField(default=10, help_text='Minimum range height in ticks for valid Asia range', validators=[django.core.validators.MinValueValidator(1)])),
                ('asia_max_range_ticks', models.PositiveIntegerField(default=200, help_text='Maximum range height in ticks for valid Asia range', validators=[django.core.validators.MinValueValidator(1)])),
                ('pre_us_start', models.CharField(default='13:00', help_text='Pre-US range start time (UTC, HH:MM format)', max_length=5)),
                ('pre_us_end', models.CharField(default='15:00', help_text='Pre-US range end time (UTC, HH:MM format)', max_length=5)),
                ('us_min_range_ticks', models.PositiveIntegerField(default=10, help_text='Minimum range height in ticks for valid Pre-US range', validators=[django.core.validators.MinValueValidator(1)])),
                ('us_max_range_ticks', models.PositiveIntegerField(default=200, help_text='Maximum range height in ticks for valid Pre-US range', validators=[django.core.validators.MinValueValidator(1)])),
                ('min_breakout_body_fraction', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Minimum candle body size as fraction of range height (0.0-1.0)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('require_atr_minimum', models.BooleanField(default=False, help_text='Whether to require minimum ATR for valid setups')),
                ('min_atr_value', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum ATR value if required', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(help_text='Asset this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='breakout_config', to='trading.tradingasset')),
            ],
            options={
                'verbose_name': 'Asset Breakout Config',
                'verbose_name_plural': 'Asset Breakout Configs',
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='trading_asset',
            field=models.ForeignKey(blank=True, help_text='Trading asset this signal belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='trading.tradingasset'),
        ),
        migrations.CreateModel(
            name='AssetEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('ASIA_RANGE', 'Asia Range'), ('LONDON_CORE', 'London Core'), ('US_CORE', 'US Core'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post')], help_text='Session phase this configuration applies to', max_length=20)),
                ('event_type', models.CharField(choices=[('NONE', 'No Event Required'), ('EIA', 'EIA Report'), ('FOMC', 'FOMC Meeting'), ('NFP', 'Non-Farm Payrolls'), ('CPI', 'Consumer Price Index'), ('GDP', 'GDP Report'), ('US_OPEN', 'US Market Open'), ('EU_OPEN', 'EU Market Open'), ('CUSTOM', 'Custom Event')], default='NONE', help_text='Type of event relevant for this phase', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Whether the event context is required for setups in this phase')),
                ('time_offset_minutes', models.IntegerField(default=0, help_text='Time offset in minutes from standard phase timing')),
                ('filter_enabled', models.BooleanField(default=True, help_text='Whether this event filter is active')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this event configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Asset this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='event_configs', to='trading.tradingasset')),
            ],
            options={
                'verbose_name': 'Asset Event Config',
                'verbose_name_plural': 'Asset Event Configs',
                'ordering': ['asset', 'phase'],
                'unique_together': {('asset', 'phase')},
            },
        ),
    ]
