# Generated by Django 5.0.14 on 2025-11-26 16:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_tradingasset_assetbreakoutconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='consecutive_candle_filter',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive candles required in breakout direction (0=disabled)'),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='eia_impulse_range_high',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum price movement for impulse range high', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='eia_impulse_range_low',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Minimum price movement for impulse range low', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='eia_max_impulse_duration_min',
            field=models.PositiveIntegerField(default=5, help_text='Maximum impulse duration in minutes after event'),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='eia_min_body_fraction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.60'), help_text='Minimum body size for EIA impulse candles (0.0-1.0)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='eia_min_impulse_atr',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Minimum ATR multiplier for EIA impulse moves', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='eia_required_impulse_strength',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Required impulse strength (0.0-1.0)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='eia_reversion_window_max_sec',
            field=models.PositiveIntegerField(default=300, help_text='Maximum seconds for reversion window (5 minutes default)'),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='eia_reversion_window_min_sec',
            field=models.PositiveIntegerField(default=30, help_text='Minimum seconds for reversion window'),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='filter_doji_breakouts',
            field=models.BooleanField(default=True, help_text='Filter out doji candle breakouts (very small body)'),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='london_max_range_ticks',
            field=models.PositiveIntegerField(default=200, help_text='Maximum range height in ticks for valid London Core range', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='london_min_range_ticks',
            field=models.PositiveIntegerField(default=10, help_text='Minimum range height in ticks for valid London Core range', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='london_range_end',
            field=models.CharField(default='12:00', help_text='London Core range end time (UTC, HH:MM format)', max_length=5),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='london_range_start',
            field=models.CharField(default='08:00', help_text='London Core range start time (UTC, HH:MM format)', max_length=5),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='max_atr_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum ATR value (for too volatile days)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='max_breakout_body_fraction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum candle body size as fraction of range height (0.0-1.0)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='max_spread_ticks',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed spread in ticks', null=True),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='max_wick_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum body-to-wick ratio for quality candles', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='min_breakout_distance_ticks',
            field=models.PositiveIntegerField(default=1, help_text='Minimum distance from range in ticks for valid breakout'),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='min_candle_body_absolute',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Minimum absolute candle body size (e.g., 0.05 USD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='min_volume_spike',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum volume spike multiplier for breakouts (e.g., 1.5 = 150% of avg)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='min_wick_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum body-to-wick ratio for quality candles', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='momentum_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Minimum momentum threshold for valid setups', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='session_volatility_cap',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Only trade breakouts when session range < this value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='volatility_throttle_min_atr',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Only trade when ATR > this value (volatility throttle)', max_digits=10, null=True),
        ),
    ]
