# Generated by Django 5.0.14 on 2025-11-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_merge_20251126_1057'),
        ('trading', '0004_tradingasset_assetbreakoutconfig_and_more'),
    ]

    operations = [
    ]
