# Generated by Django 5.0.14 on 2025-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_extend_breakout_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='us_core_trading_enabled',
            field=models.BooleanField(default=True, help_text='Whether breakouts are allowed during US Core Trading session'),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='us_core_trading_end',
            field=models.CharField(default='22:00', help_text='US Core Trading session end time (UTC, HH:MM format)', max_length=5),
        ),
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='us_core_trading_start',
            field=models.CharField(default='15:00', help_text='US Core Trading session start time (UTC, HH:MM format)', max_length=5),
        ),
        migrations.AlterField(
            model_name='asseteventconfig',
            name='phase',
            field=models.CharField(choices=[('ASIA_RANGE', 'Asia Range'), ('LONDON_CORE', 'London Core'), ('PRE_US_RANGE', 'Pre-US Range'), ('US_CORE_TRADING', 'US Core Trading'), ('US_CORE', 'US Core'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post')], help_text='Session phase this configuration applies to', max_length=20),
        ),
        migrations.AlterField(
            model_name='signal',
            name='session_phase',
            field=models.CharField(choices=[('LONDON_CORE', 'London Core'), ('PRE_US_RANGE', 'Pre-US Range'), ('US_CORE_TRADING', 'US Core Trading'), ('US_CORE', 'US Core'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post'), ('ASIAN', 'Asian Session')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workerstatus',
            name='phase',
            field=models.CharField(choices=[('ASIA_RANGE', 'Asia Range'), ('LONDON_CORE', 'London Core'), ('PRE_US_RANGE', 'Pre-US Range'), ('US_CORE_TRADING', 'US Core Trading'), ('US_CORE', 'US Core'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post'), ('FRIDAY_LATE', 'Friday Late'), ('OTHER', 'Other')], help_text='Current session phase', max_length=30),
        ),
    ]
