# Generated by Django 5.0.14 on 2025-11-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_extend_breakout_config'),
        ('trading', '0005_merge_20251126_1202'),
    ]

    operations = [
    ]
