# Generated by Django 5.0.14 on 2025-11-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_assetbreakoutconfig_us_core_trading_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakoutRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('ASIA_RANGE', 'Asia Range'), ('LONDON_CORE', 'London Core'), ('PRE_US_RANGE', 'Pre-US Range'), ('US_CORE_TRADING', 'US Core Trading')], help_text='Session phase when this range was recorded', max_length=20)),
                ('start_time', models.DateTimeField(help_text='Start time of the range period')),
                ('end_time', models.DateTimeField(help_text='End time of the range period')),
                ('high', models.DecimalField(decimal_places=6, help_text='Highest price during the range period', max_digits=12)),
                ('low', models.DecimalField(decimal_places=6, help_text='Lowest price during the range period', max_digits=12)),
                ('height_ticks', models.PositiveIntegerField(default=0, help_text='Range height in ticks')),
                ('height_points', models.DecimalField(decimal_places=6, default=0, help_text='Range height in price points (high - low)', max_digits=12)),
                ('candle_count', models.PositiveIntegerField(default=0, help_text='Number of candles captured during the range period')),
                ('atr', models.DecimalField(blank=True, decimal_places=6, help_text='ATR value at the time of range capture', max_digits=12, null=True)),
                ('valid_flags', models.JSONField(blank=True, default=dict, help_text='Range validity flags (e.g., incomplete_range, too_small, too_large, body_fraction_fail, atr_fail)')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether this range is valid for breakout trading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Asset this range belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='breakout_ranges', to='trading.tradingasset')),
                ('reference_range', models.ForeignKey(blank=True, help_text='Reference range used for trading (for US Core Trading phase)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_ranges', to='trading.breakoutrange')),
            ],
            options={
                'verbose_name': 'Breakout Range',
                'verbose_name_plural': 'Breakout Ranges',
                'ordering': ['-end_time'],
                'indexes': [models.Index(fields=['asset', 'phase', '-end_time'], name='trading_bre_asset_i_db6a9b_idx'), models.Index(fields=['-end_time'], name='trading_bre_end_tim_96001a_idx')],
            },
        ),
    ]
