# Generated by Django 5.0.14 on 2025-11-26 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_add_breakout_range_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingasset',
            name='trading_mode',
            field=models.CharField(choices=[('STRICT', 'Strict (Normal Trading)'), ('DIAGNOSTIC', 'Diagnostic (Shadow Only, Relaxed Filters)')], default='STRICT', help_text='Trading mode: STRICT for normal trading, DIAGNOSTIC for shadow-only with relaxed filters', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(help_text='Start of the diagnostic time window')),
                ('window_end', models.DateTimeField(help_text='End of the diagnostic time window')),
                ('current_phase', models.CharField(choices=[('ASIA_RANGE', 'Asia Range'), ('LONDON_CORE', 'London Core'), ('PRE_US_RANGE', 'Pre-US Range'), ('US_CORE_TRADING', 'US Core Trading'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post'), ('OTHER', 'Other')], default='OTHER', help_text='Current/last session phase', max_length=20)),
                ('trading_mode', models.CharField(choices=[('STRICT', 'Strict (Normal Trading)'), ('DIAGNOSTIC', 'Diagnostic (Shadow Only, Relaxed Filters)')], default='STRICT', help_text='Trading mode during this window', max_length=20)),
                ('last_cycle_at', models.DateTimeField(blank=True, help_text='Timestamp of the last worker cycle', null=True)),
                ('candles_evaluated', models.PositiveIntegerField(default=0, help_text='Number of candles evaluated by strategy engine')),
                ('ranges_built_asia', models.PositiveIntegerField(default=0, help_text='Number of Asia ranges built')),
                ('ranges_built_london', models.PositiveIntegerField(default=0, help_text='Number of London Core ranges built')),
                ('ranges_built_pre_us', models.PositiveIntegerField(default=0, help_text='Number of Pre-US ranges built')),
                ('ranges_built_us_core', models.PositiveIntegerField(default=0, help_text='Number of US Core Trading ranges built')),
                ('setups_generated_total', models.PositiveIntegerField(default=0, help_text='Total number of setups generated by strategy engine')),
                ('setups_generated_breakout', models.PositiveIntegerField(default=0, help_text='Number of breakout setups generated')),
                ('setups_generated_eia_reversion', models.PositiveIntegerField(default=0, help_text='Number of EIA reversion setups generated')),
                ('setups_generated_eia_trendday', models.PositiveIntegerField(default=0, help_text='Number of EIA trend day setups generated')),
                ('setups_discarded_strategy', models.PositiveIntegerField(default=0, help_text='Number of setups discarded by strategy filters')),
                ('setups_evaluated_by_risk', models.PositiveIntegerField(default=0, help_text='Number of setups evaluated by risk engine')),
                ('setups_rejected_by_risk', models.PositiveIntegerField(default=0, help_text='Number of setups rejected by risk engine')),
                ('setups_approved_by_risk', models.PositiveIntegerField(default=0, help_text='Number of setups approved by risk engine')),
                ('orders_built', models.PositiveIntegerField(default=0, help_text='Number of orders built for execution')),
                ('orders_sent_shadow', models.PositiveIntegerField(default=0, help_text='Number of shadow orders executed')),
                ('orders_sent_live', models.PositiveIntegerField(default=0, help_text='Number of live orders sent to broker')),
                ('orders_failed', models.PositiveIntegerField(default=0, help_text='Number of orders that failed')),
                ('reason_counts_strategy', models.JSONField(blank=True, default=dict, help_text='Aggregated counts of strategy rejection reason codes (e.g., {"STRAT_BODY_TOO_SMALL": 12})')),
                ('reason_counts_risk', models.JSONField(blank=True, default=dict, help_text='Aggregated counts of risk rejection reason codes (e.g., {"RISK_SPREAD_TOO_WIDE": 5})')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Asset these diagnostics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='trading.tradingasset')),
            ],
            options={
                'verbose_name': 'Asset Diagnostics',
                'verbose_name_plural': 'Asset Diagnostics',
                'ordering': ['-window_end'],
                'indexes': [models.Index(fields=['asset', '-window_end'], name='trading_ass_asset_i_110499_idx'), models.Index(fields=['-window_end'], name='trading_ass_window__fdc198_idx')],
            },
        ),
    ]
