# Generated by Django 5.0.14 on 2025-11-26 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_add_breakout_range_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSessionPhaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('ASIA_RANGE', 'Asia Range'), ('LONDON_CORE', 'London Core'), ('PRE_US_RANGE', 'Pre-US Range'), ('US_CORE_TRADING', 'US Core Trading'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post')], help_text='Session phase identifier', max_length=20)),
                ('start_time_utc', models.CharField(help_text='Phase start time in UTC (HH:MM format, e.g., "08:00")', max_length=5)),
                ('end_time_utc', models.CharField(help_text='Phase end time in UTC (HH:MM format, e.g., "12:00")', max_length=5)),
                ('is_range_build_phase', models.BooleanField(default=False, help_text='Whether this phase is used for range formation (e.g., Asia, London, Pre-US)')),
                ('is_trading_phase', models.BooleanField(default=False, help_text='Whether trading signals are generated during this phase (e.g., US Core Trading, EIA Post)')),
                ('event_type', models.CharField(choices=[('NONE', 'None'), ('EIA', 'EIA Report'), ('US_MARKET_OPEN', 'US Market Open'), ('FOMC', 'FOMC Meeting'), ('NFP', 'Non-Farm Payrolls'), ('CPI', 'Consumer Price Index'), ('GDP', 'GDP Report'), ('CUSTOM', 'Custom Event')], default='NONE', help_text='Type of event associated with this phase (NONE for regular phases)', max_length=20)),
                ('requires_event', models.BooleanField(default=False, help_text='Whether this phase is only valid when the associated event is present')),
                ('event_offset_minutes', models.IntegerField(default=0, help_text='Time offset in minutes from the event (e.g., -5 for 5 minutes before)')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this phase is active for this asset')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this phase configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Asset this phase configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='session_phase_configs', to='trading.tradingasset')),
            ],
            options={
                'verbose_name': 'Asset Session Phase Config',
                'verbose_name_plural': 'Asset Session Phase Configs',
                'ordering': ['asset', 'phase'],
                'indexes': [models.Index(fields=['asset', 'enabled'], name='trading_ass_asset_i_0512cf_idx')],
                'unique_together': {('asset', 'phase')},
            },
        ),
    ]
