# Generated by Django 5.0.14 on 2025-11-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_merge_20251126_1747'),
        ('trading', '0007_add_breakout_range_model'),
    ]

    operations = [
    ]
