# Generated by Django 5.0.14 on 2025-11-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_add_asset_session_phase_config'),
        ('trading', '0008_merge_20251126_2120'),
    ]

    operations = [
    ]
