# Generated by Django 5.2.8 on 2025-11-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_add_asset_session_phase_config'),
        ('trading', '0008_add_diagnostics_and_trading_mode'),
    ]

    operations = [
    ]
