# Generated by Django 5.0.14 on 2025-11-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_merge_20251126_2308'),
        ('trading', '0009_merge_20251126_2338'),
    ]

    operations = [
    ]
