# Generated by Django 5.0.14 on 2025-11-27 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_merge_20251126_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsessionphaseconfig',
            name='phase',
            field=models.CharField(choices=[('ASIA_RANGE', 'Asia Range'), ('LONDON_CORE', 'London Core'), ('PRE_US_RANGE', 'Pre-US Range'), ('US_CORE_TRADING', 'US Core Trading'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post'), ('OTHER', 'Other')], help_text='Session phase identifier', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetPriceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(blank=True, decimal_places=6, help_text='Current bid price', max_digits=12, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=6, help_text='Current ask price', max_digits=12, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=6, help_text='Current spread', max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('asset', models.OneToOneField(help_text='Asset this price status belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='price_status', to='trading.tradingasset')),
            ],
            options={
                'verbose_name': 'Asset Price Status',
                'verbose_name_plural': 'Asset Price Statuses',
            },
        ),
    ]
