# Generated by Django 5.0.14 on 2025-11-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_merge_20251126_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsessionphaseconfig',
            name='phase',
            field=models.CharField(choices=[('ASIA_RANGE', 'Asia Range'), ('LONDON_CORE', 'London Core'), ('PRE_US_RANGE', 'Pre-US Range'), ('US_CORE_TRADING', 'US Core Trading'), ('EIA_PRE', 'EIA Pre'), ('EIA_POST', 'EIA Post'), ('OTHER', 'Other')], help_text='Session phase identifier', max_length=20),
        ),
    ]
