# Generated by Django 5.0.14 on 2025-11-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_add_asset_price_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Time of the price snapshot')),
                ('price_mid', models.DecimalField(decimal_places=6, help_text='Mid price (average of bid and ask)', max_digits=12)),
                ('price_bid', models.DecimalField(blank=True, decimal_places=6, help_text='Bid price', max_digits=12, null=True)),
                ('price_ask', models.DecimalField(blank=True, decimal_places=6, help_text='Ask price', max_digits=12, null=True)),
                ('asset', models.ForeignKey(help_text='Asset this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='trading.tradingasset')),
            ],
            options={
                'verbose_name': 'Price Snapshot',
                'verbose_name_plural': 'Price Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='trading_pri_asset_i_a14838_idx')],
            },
        ),
    ]
