# Generated by Django 5.0.14 on 2025-11-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_add_asset_price_status'),
        ('trading', '0011_alter_assetsessionphaseconfig_phase'),
    ]

    operations = [
    ]
