# Generated by Django 5.0.14 on 2025-11-29 07:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_add_price_snapshot_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingasset',
            name='broker',
            field=models.CharField(choices=[('IG', 'IG'), ('MEXC', 'MEXC')], default='IG', help_text='Broker to use for trading this asset (IG or MEXC)', max_length=16),
        ),
        migrations.AddField(
            model_name='tradingasset',
            name='broker_symbol',
            field=models.CharField(blank=True, help_text='IG-EPIC or MEXC-Symbol (if different from epic field)', max_length=64),
        ),
        migrations.AddField(
            model_name='tradingasset',
            name='is_crypto',
            field=models.BooleanField(default=False, help_text='Whether this is a cryptocurrency asset'),
        ),
        migrations.AddField(
            model_name='tradingasset',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Lot size for this asset', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradingasset',
            name='max_size',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Maximum order/position size', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradingasset',
            name='min_size',
            field=models.DecimalField(decimal_places=5, default=Decimal('1'), help_text='Minimum order/position size', max_digits=10),
        ),
        migrations.AddField(
            model_name='tradingasset',
            name='quote_currency',
            field=models.CharField(default='USD', help_text='Quote currency for this asset (e.g., USD, EUR, USDT)', max_length=10),
        ),
    ]
