# Generated by Django 5.0.14 on 2025-11-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_add_price_snapshot_model'),
        ('trading', '0012_merge_20251127_2156'),
    ]

    operations = [
    ]
