# Generated by Django 5.0.14 on 2025-11-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_tradingasset_broker_tradingasset_broker_symbol_and_more'),
        ('trading', '0013_merge_20251128_0802'),
    ]

    operations = [
    ]
