# Generated by Django 5.0.14 on 2025-11-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_merge_20251129_0919'),
        ('trading', '0014_merge_20251129_0937'),
    ]

    operations = [
    ]
