# Generated by Django 5.0.14 on 2025-11-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0015_merge_20251129_0948"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetpricestatus",
            name="last_strategy_status",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Latest strategy engine status message for this asset",
            ),
        ),
    ]
