# Generated by Django 5.0.14 on 2025-11-30 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0016_assetpricestatus_last_strategy_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="breakoutrange",
            name="last_adjusted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last manual adjustment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="breakoutrange",
            name="last_adjusted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last adjusted the manual high/low",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adjusted_breakout_ranges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="breakoutrange",
            name="manual_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional manual override for the range high",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="breakoutrange",
            name="manual_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional manual override for the range low",
                max_digits=12,
                null=True,
            ),
        ),
    ]
