# Generated by Django 5.0.14 on 2025-12-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_breakoutrange_last_adjusted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbreakoutconfig',
            name='max_candle_distance_ticks',
            field=models.PositiveIntegerField(default=10, help_text='Maximum distance of candle (low for LONG, high for SHORT) from range boundary in ticks'),
        ),
    ]
