# Generated by Django 5.0.14 on 2025-12-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_add_max_candle_distance_ticks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingasset',
            name='broker',
            field=models.CharField(choices=[('IG', 'IG'), ('MEXC', 'MEXC'), ('KRAKEN', 'Kraken')], default='IG', help_text='Broker to use for trading this asset (IG, MEXC, or Kraken)', max_length=16),
        ),
        migrations.AlterField(
            model_name='tradingasset',
            name='broker_symbol',
            field=models.CharField(blank=True, help_text='Broker-specific symbol (e.g., IG-EPIC, MEXC-Symbol, or Kraken-Symbol) if different from epic field', max_length=64),
        ),
    ]
