# Generated by Django 5.0.14 on 2025-12-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_add_kraken_broker_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='broker_error_message',
            field=models.TextField(blank=True, help_text='Error message from broker if order failed', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='broker_order_id',
            field=models.CharField(blank=True, help_text='Broker-specific order/deal ID from place_order() response', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='broker_status',
            field=models.CharField(blank=True, help_text='Order status from broker (e.g., OPEN, PENDING, REJECTED)', max_length=50, null=True),
        ),
    ]
