# Generated by Django 5.0.14 on 2025-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_add_broker_order_fields_to_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingasset',
            name='auto_trade',
            field=models.BooleanField(default=False, help_text='If true, automatically execute live trades when signals are generated with allowed risk status'),
        ),
    ]
