# Generated by Django 5.0.14 on 2025-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_add_auto_trade_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingasset',
            name='max_pullback_ticks',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of ticks for a valid pullback'),
        ),
        migrations.AddField(
            model_name='tradingasset',
            name='min_break_ticks',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of ticks for a valid breakout'),
        ),
    ]
