# Generated by Django 5.0.14 on 2025-12-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_tradingasset_max_pullback_ticks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingasset',
            name='breakout_state',
            field=models.CharField(choices=[('IN_RANGE', 'IN_RANGE'), ('BROKEN_LONG', 'BROKEN_LONG'), ('BROKEN_SHORT', 'BROKEN_SHORT')], default='IN_RANGE', help_text='Current breakout state of the asset', max_length=20),
        ),
    ]
