import logging

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.exceptions import ImproperlyConfigured
from django.utils import timezone

from .models import Signal, Trade, WorkerStatus
from core.services.broker import create_ig_broker_service, BrokerError, AuthenticationError

logger = logging.getLogger(__name__)


@login_required
def signal_dashboard(request):
    """
    Signal Dashboard - Main view showing all active trading signals.
    
    Displays signals from the database that are generated by the real
    Strategy Engine, KI Layer, and Risk Engine services.
    """
    signals = Signal.objects.filter(status='ACTIVE')
    active_count = signals.count()
    
    context = {
        'signals': signals,
        'active_count': active_count,
    }
    
    return render(request, 'trading/signal_dashboard.html', context)


@login_required
def signal_detail(request, signal_id):
    """
    Trade Detail Panel - Detailed view of a specific signal.
    
    Displays full signal details including KI evaluation and Risk Engine results.
    """
    try:
        signal = Signal.objects.get(id=signal_id)
    except (Signal.DoesNotExist, ValueError):
        # Signal not found - redirect to dashboard
        return redirect('signal_dashboard')
    
    context = {
        'signal': signal,
    }
    
    return render(request, 'trading/signal_detail.html', context)


@login_required
@require_http_methods(['POST'])
def execute_live_trade(request, signal_id):
    """
    Execute a live trade for a signal.
    """
    try:
        signal = Signal.objects.get(id=signal_id)
        
        if not signal.can_execute_live:
            return JsonResponse({
                'success': False,
                'error': 'Live Trade nicht erlaubt basierend auf Risk Engine Status.'
            }, status=400)
        
        # Create the trade
        trade = Trade.objects.create(
            signal=signal,
            trade_type='LIVE',
            entry_price=signal.trigger_price,
            stop_loss=signal.gpt_corrected_sl or signal.stop_loss,
            take_profit=signal.gpt_corrected_tp or signal.take_profit,
            position_size=signal.gpt_corrected_size or signal.position_size,
        )
        
        # Update signal status
        signal.status = 'EXECUTED'
        signal.executed_at = timezone.now()
        signal.save()
        
        return JsonResponse({
            'success': True,
            'message': 'Live Trade erfolgreich ausgeführt!',
            'trade_id': str(trade.id)
        })
        
    except Signal.DoesNotExist:
        return JsonResponse({
            'success': False,
            'error': 'Signal nicht gefunden.'
        }, status=404)


@login_required
@require_http_methods(['POST'])
def execute_shadow_trade(request, signal_id):
    """
    Execute a shadow trade for a signal.
    """
    try:
        signal = Signal.objects.get(id=signal_id)
        
        # Create the shadow trade
        trade = Trade.objects.create(
            signal=signal,
            trade_type='SHADOW',
            entry_price=signal.trigger_price,
            stop_loss=signal.gpt_corrected_sl or signal.stop_loss,
            take_profit=signal.gpt_corrected_tp or signal.take_profit,
            position_size=signal.gpt_corrected_size or signal.position_size,
        )
        
        # Update signal status
        signal.status = 'SHADOW'
        signal.save()
        
        return JsonResponse({
            'success': True,
            'message': 'Shadow Trade erfolgreich gestartet!',
            'trade_id': str(trade.id)
        })
        
    except Signal.DoesNotExist:
        return JsonResponse({
            'success': False,
            'error': 'Signal nicht gefunden.'
        }, status=404)


@login_required
@require_http_methods(['POST'])
def reject_signal(request, signal_id):
    """
    Reject/dismiss a signal.
    """
    try:
        signal = Signal.objects.get(id=signal_id)
        signal.status = 'REJECTED'
        signal.save()
        
        return JsonResponse({
            'success': True,
            'message': 'Signal verworfen.'
        })
        
    except Signal.DoesNotExist:
        return JsonResponse({
            'success': False,
            'error': 'Signal nicht gefunden.'
        }, status=404)


@login_required
def trade_history(request):
    """
    Trade history view - Shows executed and shadow trades with pagination.
    """
    trade_list = Trade.objects.select_related('signal').all()
    
    # Paginate results
    paginator = Paginator(trade_list, 25)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'trades': page_obj,
        'page_obj': page_obj,
    }
    
    return render(request, 'trading/trade_history.html', context)


# API Endpoints for HTMX/AJAX integration

@login_required
def api_signals(request):
    """
    GET /api/signals - Return list of active signals as JSON.
    """
    signals = list(Signal.objects.filter(status='ACTIVE').values())
    return JsonResponse({'signals': signals})


@login_required
def api_signal_detail(request, signal_id):
    """
    GET /api/trade/{id} - Return signal details as JSON.
    """
    try:
        signal = Signal.objects.get(id=signal_id)
        data = {
            'id': str(signal.id),
            'setup_type': signal.setup_type,
            'session_phase': signal.session_phase,
            'direction': signal.direction,
            'trigger_price': str(signal.trigger_price),
            'range_high': str(signal.range_high),
            'range_low': str(signal.range_low),
            'stop_loss': str(signal.stop_loss),
            'take_profit': str(signal.take_profit),
            'position_size': str(signal.position_size),
            'ki_reasoning': signal.ki_reasoning,
            'gpt_confidence': str(signal.gpt_confidence),
            'gpt_reasoning': signal.gpt_reasoning,
            'risk_status': signal.risk_status,
            'risk_reasoning': signal.risk_reasoning,
            'status': signal.status,
            'can_execute_live': signal.can_execute_live,
        }
        return JsonResponse(data)
    except Signal.DoesNotExist:
        return JsonResponse({'error': 'Signal nicht gefunden.'}, status=404)


@login_required
def api_account_state(request):
    """
    GET /api/account-state - Return current account state (balance, margin) from IG Broker.
    
    Returns JSON with account information including:
    - balance: Current account balance
    - available: Available funds for trading
    - equity: Total equity including open positions
    - margin_used: Margin currently in use
    - margin_available: Available margin
    - unrealized_pnl: Unrealized profit/loss
    - currency: Account currency
    - account_name: Account name
    - account_id: Account ID
    - timestamp: When the data was fetched
    - connected: Whether the broker is connected
    """
    try:
        # Create and connect to broker
        broker = create_ig_broker_service()
        broker.connect()
        
        try:
            # Get account state
            account_state = broker.get_account_state()
            
            return JsonResponse({
                'success': True,
                'data': {
                    'account_id': account_state.account_id,
                    'account_name': account_state.account_name,
                    'balance': str(account_state.balance),
                    'available': str(account_state.available),
                    'equity': str(account_state.equity),
                    'margin_used': str(account_state.margin_used),
                    'margin_available': str(account_state.margin_available),
                    'unrealized_pnl': str(account_state.unrealized_pnl),
                    'currency': account_state.currency,
                    'timestamp': account_state.timestamp.isoformat() if account_state.timestamp else None,
                },
                'connected': True,
            })
        finally:
            # Always disconnect
            broker.disconnect()
            
    except ImproperlyConfigured as e:
        logger.warning(f"IG Broker not configured: {e}")
        return JsonResponse({
            'success': False,
            'error': 'Broker nicht konfiguriert. Bitte IG Broker im Admin-Bereich konfigurieren.',
            'connected': False,
        }, status=503)
    except AuthenticationError as e:
        logger.error(f"IG Broker authentication failed: {e}")
        return JsonResponse({
            'success': False,
            'error': 'Broker-Authentifizierung fehlgeschlagen.',
            'connected': False,
        }, status=401)
    except (BrokerError, ConnectionError) as e:
        logger.error(f"IG Broker error: {e}")
        return JsonResponse({
            'success': False,
            'error': f'Broker-Fehler: {str(e)}',
            'connected': False,
        }, status=503)
    except Exception as e:
        logger.error(f"Unexpected error fetching account state: {e}")
        return JsonResponse({
            'success': False,
            'error': 'Ein unerwarteter Fehler ist aufgetreten.',
            'connected': False,
        }, status=500)


@login_required
def api_worker_status(request):
    """
    GET /api/worker/status - Return current worker status.
    
    Returns JSON with worker status information including:
    - worker_status: ONLINE or OFFLINE (based on last_run_at threshold)
    - last_run_at: Timestamp of last worker loop
    - phase: Current session phase
    - epic: Current instrument being monitored
    - price_info: Bid/Ask/Spread
    - setup_count: Number of setups found in last run
    - diagnostic_message: Human-readable status message
    - worker_interval: Expected worker loop interval
    """
    try:
        # Get the current worker status
        status = WorkerStatus.get_current()
        
        if status is None:
            return JsonResponse({
                'success': True,
                'worker_status': 'NO_DATA',
                'status_message': 'Noch keine Worker-Statusdaten vorhanden',
                'data': None,
            })
        
        # Determine if worker is ONLINE or OFFLINE
        # ONLINE if last heartbeat is within 2 * worker_interval
        now = timezone.now()
        threshold_seconds = status.worker_interval * 2
        time_since_last_run = (now - status.last_run_at).total_seconds()
        
        if time_since_last_run <= threshold_seconds:
            worker_status = 'ONLINE'
            status_message = 'Worker ist aktiv'
        else:
            worker_status = 'OFFLINE'
            status_message = f'Worker ist seit {int(time_since_last_run)}s inaktiv'
        
        # Build response data
        data = {
            'last_run_at': status.last_run_at.isoformat(),
            'phase': status.phase,
            'epic': status.epic,
            'price_info': {
                'bid': str(status.bid_price) if status.bid_price else None,
                'ask': str(status.ask_price) if status.ask_price else None,
                'spread': str(status.spread) if status.spread else None,
            },
            'setup_count': status.setup_count,
            'diagnostic_message': status.diagnostic_message,
            'worker_interval': status.worker_interval,
            'seconds_since_last_run': int(time_since_last_run),
        }
        
        return JsonResponse({
            'success': True,
            'worker_status': worker_status,
            'status_message': status_message,
            'data': data,
        })
        
    except Exception as e:
        logger.error(f"Error fetching worker status: {e}")
        return JsonResponse({
            'success': False,
            'worker_status': 'ERROR',
            'status_message': f'Fehler: {str(e)}',
            'data': None,
        }, status=500)
